on: push
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - uses: daohoangson/comment-on-github@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: "Check out this message!"
